name: Zad2 - GHAction example solution  

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, tag and push Docker image to DockerHub
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.memory.outputs.new_tag }}
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      -
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/zad2
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zad2:cache 
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/zad2:cache  
          tags: ${{ steps.meta.outputs.tags }}
      
      -
        name: Interjobs output declaration
        id: memory
        run: echo "new_tag=${{ steps.meta.outputs.version }}" >> "$GITHUB_OUTPUT" 
        shell: bash

  cd_step:
    name: Modify K8s deployment and configmaps manifests 
    
    env:
      NEW_TAG: ${{ needs.ci_step.outputs.image_tag }}
    
    runs-on: ubuntu-latest
    needs: ci_step
    
    steps:
      - 
        name: Check out the config_repo
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.GIT_USERNAME }}/config_repo
          ref: main
          token: ${{ secrets.GIT_TOKEN }}
      
      -
        name: Configure Git
        run: |
          git config user.email ${{ vars.GIT_EMAIL }} 
          git config user.name ${{ vars.GIT_USERNAME }}

      - 
        name: Modify the K8s manifests
        run: |         
          sed -i 's/${{ vars.DOCKERHUB_USERNAME }}\/zad2:.*/${{ vars.DOCKERHUB_USERNAME }}\/zad2:${{ env.NEW_TAG }}/g' ./deployment.yaml
          sed -i 's/${{ vars.DOCKERHUB_USERNAME }}\/zad2:.*/${{ vars.DOCKERHUB_USERNAME }}\/zad2:${{ env.NEW_TAG }}/g' ./configmap.yaml
       
      -
        name: Commit and push to config repo
        run: |   
          git add .
          git commit -m "New image with tag: ${{ env.NEW_TAG }}"
          git push origin main
          
